"""added Passport Column

Revision ID: 1825b868d8bd
Revises: 6de2abf4f14a
Create Date: 2025-06-02 20:42:59.205233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1825b868d8bd'
down_revision: Union[str, None] = '6de2abf4f14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('passport', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'passport')
    # ### end Alembic commands ###
