"""added subscription_id to member table

Revision ID: e7f4f1bfdd36
Revises: 9b655244ed63
Create Date: 2025-06-02 23:50:45.647203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f4f1bfdd36'
down_revision: Union[str, None] = '9b655244ed63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('subscription_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'subscription_id')
    # ### end Alembic commands ###
